### ISSUE TITLE
Intel i915 error: intel_do_flush_locked

### ISSUE THREAD

**Issue by buseche** [snapcrafters/tmnationsforever#10]
Greetings for everyone

I've installed the TM in my PC, but when i execute the program, the console returns this message:

intel_do_flush_locked failed: Input/output error

My PC have this properties:

OS: Linux Mint Sonya XFCE  64-Bit
RAM: 1 GB
GPU: OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) 865G 
OpenGL version string: 1.3 Mesa 17.3.3
OpenGL extensions:

i have the MESA drivers and VULKAN.

**Comment by galgalesh** [comment]
This should be fixed in the latest version. Please reopen the issue if you still experience this issue.
