### ISSUE TITLE
Won't download TM Nations Forever

### ISSUE THREAD

**Issue by vojta-horanek** [snapcrafters/tmnationsforever#13]
When I open the snap, the installer pops up, but never downloads anything and just says "Preparing Windows enviroment"

![issue](https://user-images.githubusercontent.com/12630566/41868172-8bae7dc6-78b5-11e8-90dc-9c7f7a5128b6.png)
Some info:
```
snap     2.30
snapd    2.30
series   16
manjaro  
kernel   4.14.48-2-MANJARO
```
`tmnationsforever  2.11.26  17    snapcrafters  -`

[Terminal log](https://pastebin.com/Zdft8WAy) (it's quite long, that's why pastebin)

**Comment by Ads20000** [comment]
Your version of snapd is outdated, it should be 2.33, I can see that the package in Manjaro is outdated and will create a topic on the snapcraft forums about it... In theory snapd should update itself without a new Manjaro package but presumably that re-exec feature is not working on Manjaro, I'll ask about that too.

**Comment by vojta-horanek** [comment]
Installed the latest snapd (2.33) from AUR everything is working now, thanks
