### ISSUE TITLE
DirectX is missing

### ISSUE THREAD

**Issue by BeratAdemi** [snapcrafters/tmnationsforever#15]
System:
Debian 9.4
snap core version: 16-2.33.1 (stable)
tmnationsforever version: 2.11.26 (stable)

Issue:
After the last reboot (no other changes made) I tried to open tmnationsforever snap.

It resulted in a popup telling me that DirectX was missing and closed the program.

A reinstall did not solve the problem.
After the reinstall it told me: 
"DirectX 9.0 initialization failed!
      "Direct3DCreator9"

Please check if this version of DirectX is properly installed properly on your computer"

Neither a reboot worked.

I am not sure what else to attach to this.
I don't exactly know where to find logs that might be interesting.
Also I'm not sure at all what information could be interesting for solving the issue.

I was not able to reproduce that error on another machine.

**Comment by BeratAdemi** [comment]
duplicate of issue #4 

running from terminal gives the same output that is given at issue #4 

Graphics: NVIDIA GeForce 8600 GT

**Comment by galgalesh** [comment]
This should be fixed in the latest version. Please reopen the issue if you still experience this issue.
