### ISSUE TITLE
Window doesn't close when quitting.

### ISSUE THREAD

**Issue by BryanFRitt** [snapcrafters/tmnationsforever#17]
Window doesn't close when quitting. After closing quit window doesn't close itself. It just stays open. Clicking on x doesn't close the window either. Just starting `xkill` closes the window(note: right click to cancel 'the click on window to close it'), I don't even have to left click on the window to close it.

**Comment by galgalesh** [comment]
This should be fixed in the latest version. Please reopen the issue if you still experience this issue.
