### ISSUE TITLE
How to open graphic settings window?

### ISSUE THREAD

**Issue by milancpp** [snapcrafters/tmnationsforever#18]
Hi there, thanks for this awesome package!

Is there a way to open the graphic settings window that normally opens when launching TM on Windows? Within the game only the resolution can be adjusted, no further settings.

Thanks!

**Comment by leodom** [comment]
More settings can be accessed by launching the game with the command _tmnationsforever.launcher_

**Comment by michas0602** [comment]
Running "tmnationsforever.launcher" does not work.
`Linux:~$ tmnationsforever.launcher

Der Befehl 'tmnationsforever.launcher' wurde nicht gefunden, kann aber installiert werden mit:

sudo snap install tmnationsforever
`

The snap is installed and works "fine" - except the possibility to change to fullscreen. How to play this game in fullscreen?
Alt-Enter is just semi-fullscreen, the bottombar/menubar is still visible.

I assume the game is just missing to launch graphic-settings somehow before its starting.

**Comment by stoohoff** [comment]
tmnationsforever.launcher says ,,command not found”. Is there some another way?

**Comment by azuwey** [comment]
What I have done is opened the `~/snap/tmnationsforever/common/.wine/drive_c/Program Files (x86)/TmNationsForever` folder renamed temporarily `TmForever.exe` to `TmForever.exe.bak` and `TmForeverLauncher.exe` to `TmForever.exe` and launched the game with `tmnationsforever` command, setup my settings and quit the launcher after that I renamed every back to normal, and launched the game normally.

**Comment by galgalesh** [comment]
With most sommelier-core snaps, you can run `snap-name.wine` to run arbitrary commands in wine inside of the snap. You can use this to show the launcher:

```shell
tmnationsforever.wine "C:/Program Files (x86)/TmNationsForever/TmForeverLauncher.exe"
```

This command also accepts absolute paths. So this also runs the launcher:

```shell
tmnationsforever.wine "$HOME/snap/tmnationsforever/common/.wine/drive_c/Program Files (x86)/TmNationsForever/TmForeverLauncher.exe"
```

**Comment by galgalesh** [comment]
The next version of this snap will run the launcher first so you can always change graphics settings. It should be available for testing in the `edge` channel soon.
