### ISSUE TITLE
19.04 ubuntu unable to start game

### ISSUE THREAD

**Issue by vudududu** [snapcrafters/tmnationsforever#21]
snap    2.38.1
snapd   2.38.1
series  16
ubuntu  19.04
kernel  5.0.0-13-generic

sudo snap run tmnationsforever    
mkdir: cannot create directory ‘/run/user/0’: Permission denied
/snap/tmnationsforever/28/bin/sommelier: line 222:  1637 Segmentation fault      (core dumped) env WINEARCH="${WINEARCH}" WINEPREFIX="${WINEPREFIX}" "${WINELOADER}" wineboot --init 2>&1
      1638                       (core dumped) | yad --progress --title="Preparing Windows environment" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --pulsate
/snap/tmnationsforever/28/bin/sommelier: line 223:  1636 Segmentation fault      (core dumped) yad --timeout=15 --timeout-indicator=bottom --text="${NOTICE}" --no-escape --width=460 --center --no-buttons --splash --on-top
/snap/tmnationsforever/28/bin/sommelier: line 10:  1642 Segmentation fault      (core dumped) wget "${INSTALL_URL}" -O "${TMPDIR}/${INSTALL_EXE}" 2>&1
      1643                       (core dumped) | perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Downloading... \2 (\3)/'
      1644                       (core dumped) | yad --progress --title="${INSTALL_EXE}" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape
/snap/tmnationsforever/28/bin/sommelier: line 10:  1648 Segmentation fault      (core dumped) env WINEARCH="${WINEARCH}" WINEPREFIX="${WINEPREFIX}" "${WINELOADER}" "${TMPDIR}/${INSTALL_EXE}" /silent
rm: cannot remove '/tmp/tmnationsforever_setup.exe': No such file or directory
/snap/tmnationsforever/28/bin/sommelier: line 40: cd: /root/snap/tmnationsforever/common/.wine/drive_c/Program Files/TmNationsForever: No such file or directory
/snap/tmnationsforever/28/bin/sommelier: line 34:  1653 Segmentation fault      (core dumped) env WINEARCH="${WINEARCH}" WINEPREFIX="${WINEPREFIX}" "${WINELOADER}" "${WINE_EXE}"

**Comment by popey** [comment]
I'm seeing similar on 18.04.

```
wine: Unhandled page fault on read access to 0x0000006c at address 0x403365 (thread 002e), starting debugger...
Can't attach process 0008: error 5
removed '/tmp/tmnationsforever_setup.exe'
/snap/tmnationsforever/31/bin/sommelier: line 40: cd: /home/alan/snap/tmnationsforever/common/.wine/drive_c/Program Files/TmNationsForever: No such file or directory
```

**Comment by popey** [comment]
Interestingly I think I see why it failed for me. I was using my computer while the tmnationsforever setup exe was being downloaded. Immediately after download, the setup window appears, with the [Cancel] button highlighted, and then moves onto the setup wizard, also with [Cancel] highlighted. As I was still using my laptop while the setup ran, I suspect I inadvertently hit the [Cancel] button by mistake. This left a broken install of tmn behind. I just re-ran it, which re-ran the setup and now it works just fine. 

This was with revision 31 in the edge channel, which I'm going to promote to stable. I recommend anyone having problems should try removing and reinstalling the snap, and don't touch the keyboard while the setup runs. Let it finish and see if it works.

I will also trigger a new build to use newer wine, as that may also help some people, and will test that later.

**Comment by popey** [comment]
Ok, I've tested revision 32, try uninstalling and reinstalling the snap and see if that resolves this issue. Do re-open or open a new one if not.
