### ISSUE TITLE
TM United Forever - snap clone successful

### ISSUE THREAD

**Issue by seffs** [snapcrafters/tmnationsforever#27]
Hi there, I thought this was worth sharing and sparing the hassle to tweak the files

Rebuild the snap for TM United Forever. Only (relevant) single line of code to change is the "INSTALL_URL" one since TMUF installer can be downloaded directly too, besides renaming the installation path in the wrappers. 

Game was set up successfully in Ubuntu 18.04. Some framedrops compared to tmnationsforever and the pulseaudio plug needs to be connected manually.

**Comment by pizzadude** [comment]
You probably should include in the snap store description, that you need to provide the CD key, so novice users don't get confused.

**Comment by seffplusplus** [comment]
Done. snap is live

**Comment by leodom** [comment]
Hi there, wondering if the same thing would work to install TM2 ?
Building snap using an url to the TMP2 installer ? :P

**Comment by seffplusplus** [comment]
It sounds doable. You would need to update installation directories too. Should be interesting to compare its performance against Steam's proton which is proficient already
