### ISSUE TITLE
No sound and crashs in Debian Stretch

### ISSUE THREAD

**Issue by newton-jose** [snapcrafters/tmnationsforever#28]
No sound and eventual crashes in my tmnationsforever.
Some idea? 
Linux newton 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64 GNU/Linux

**Comment by galgalesh** [comment]
Can you run the app via the CLI `tmnationsforever` and show the output?

**Comment by galgalesh** [comment]
Closing this bug due to inactivity. Please reopen the bug if you can provide the requested output.
