### ISSUE TITLE
Cannot play with local network

### ISSUE THREAD

**Issue by nicolalandro** [snapcrafters/tmnationsforever#29]
You cannot see the other players on Local network with zerotier.

**Comment by nicolalandro** [comment]
I find a Trik that can work: run the command `TmForever.exe /lan /join=192.168.x.x` but how to append this command to `tmnationsforever` command? It seams do not work. Where I can find the .exe file?

**Comment by seffs** [comment]
Based on `sommelier-core` script, this should be doable. Update to latest version in the store and launch `tmnationsforever  /lan /join=192.168.x.x`

**Comment by nicolalandro** [comment]
Thank you, I will Try.

**Comment by galgalesh** [comment]
It's not clear if this is an issue with

* this snap
* or wine
* or the app

Do you have the same issues when running it in playonlinux?

**Comment by galgalesh** [comment]
The next version of this snap will run the launcher first so you can easily change network and peer settings. It should be available for testing in the `edge` channel soon.

Please reopen if this doesn't fix your issue.
