### ISSUE TITLE
DirectX9 not found error

### ISSUE THREAD

**Issue by fishears** [snapcrafters/tmnationsforever#4]
Installed the snap and launched. All downloaded and installed but when the game exe launches I get an "Error: Could not find DirectX9" and this output to terminal:
```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
0031:err:wgl:X11DRV_WineGL_InitOpenglInfo  couldn't initialize OpenGL, expect problems
0031:fixme:win:EnumDisplayDevicesW ((null),0,0x33f0a4,0x00000000), stub!
```
Clicking "OK" on this leads to "DirectX9 initialisation falied! 'Direct3DCreate9' Please check if this version of DrectX is properly installed on your computer" and this output to terminal:

```
0031:fixme:dinput:IDirectInputDevice2WImpl_EnumEffects (this=0x184f94,0x8fa9b0,0x144ac40,0x00000003): stub!
0031:fixme:dinput:IDirectInputDevice2WImpl_EnumEffects (this=0x186624,0x8fa9b0,0x144ad20,0x00000003): stub!
```
I have Nvidia GTX750ti with driver 396.24 on Ubuntu 18.04

**Comment by izznogooood** [comment]
+1

Ubuntu 18.04, minimum install.
Nvidia 390 Driver.

**Comment by koenlek** [comment]
Would be great if it can be fixed for the Nvidia 396 or 410 drivers. Please note that the 410 drivers are now the official release (the "long-lived branch"), so starting to support that would be great.

**Comment by galgalesh** [comment]
This should be fixed for latest nvidia drivers, please reopen the issue if you still have issues.

**Comment by msplival** [comment]
Hi. I have this issue on Ubuntu 20.04 (Neon variant, to be precise): 

```mario@MP50 ~> snap list | grep tmnations
tmnationsforever        2.11.26                     47     latest/stable  snapcrafters  -
mario@MP50 ~> tmnationsforever
Starting application..
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error:  GLXBadContext
  Request Major code 151 (GLX)
  Request Minor code 6 ()
  Error Serial #182
  Current Serial #181
mario@MP50 ~> 
```

**Comment by galgalesh** [comment]
It seems the GPU(drivers) are not found correctly. What GPU are you using?
And which drivers do you have installed?

**Comment by msplival** [comment]
I have Nvidia 1060, and I have installed nvidia-compute-utils-470 package. I think those are working fine as I have hw acceleration in, say, nexuiz, or xonototic, and such games.
